name: if branch exists
on: [workflow_dispatch]
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout child
      uses: actions/checkout@v3
      with:
        repository: kudrinyaroslav/child
        fetch-depth: 0
        path: ./child
        
    - name: Check if branch exists
      run: |
        cd child
        git push origin --delete new-branch-name
#        if git branch -a | grep -q "refs/remotes/origin/new-branch-name"; then
        
#        fi

