name: if branch exists
on: [workflow_dispatch]
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Check if branch exists
      run: |
        git clone git@github.com:kudrinyaroslav/child.git
        cd child
        if git branch -a | grep "origin/new-branch-name"; then
         git push origin --delete new-branch-name
        fi

