name: if branch exists
on: [workflow_dispatch]
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout child
      uses: actions/checkout@v3
      with:
        repository: kudrinyaroslav/child
        ref: main
        fetch-depth: 0
        path: ./child
        
    - name: Check if branch exists
      run: |
        git branch -a | grep -q "refs/remotes/origin/new-branch-name"
