curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$repo/pulls" -d '{"head":"new-branch-name","base":"main","title":"Update from template repository"}'
