name: Copy Files
on:
  push:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Commit changes
      run: |
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$repo/pulls" -d '{"head":"new-branch-name","base":"main","title":"Update from template repository"}'
