name: Copy Files

on:
  push:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout template
      uses: actions/checkout@v2
      with:
        repository: kudrinyaroslav/template
        ref: main
        fetch-depth: 0
    - name: Copy files to child
      run: |
        ls
          
          
#       - name: Create pull request
#         uses: peter-evans/create-pull-request@v3.10.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           branch: new-branch-name
#           title: "Copy files from template to child"
#           body: "This PR copies the necessary files from template to child"
#           draft: false
