name: Copy Files

on:
  push:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template
        run:
          git clone git clone git@github.com:kudrinyaroslav/template.git
          git clone git@github.com:kudrinyaroslav/child.git
          cp -r ./template/* ./child/
          cd child
          git checkout -b new-branch-name
          git add .
          git commit -m "Copy files from template to child"
          
          
#       - name: Create pull request
#         uses: peter-evans/create-pull-request@v3.10.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           branch: new-branch-name
#           title: "Copy files from template to child"
#           body: "This PR copies the necessary files from template to child"
#           draft: false
