name: sync wiht template
on:
  push:
  schedule:
  - cron: '*/10 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout template repository
      uses: actions/checkout@v2
      with:
        repository: kudrinyaroslav/child
        ref: main
        
    - name: Setup SSH agent
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_rsa
    - name: Create brunch
      run: |
        git checkout -b sync-branch
        git push -u origin sync-branch
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Sync with template'
        branch: sync-branch
        title: 'Sync with template'
        body: 'This pull request syncs the child repo'
