name: Copy Files
on: [workflow_dispatch]
env:
  TEMPLATE_REPO_NAME: template
  CHILD_REPO_NAME: child
  TEMP_BRANCH_NAME: new-branch-name
  CHILD_MAIN_BRANCH: main
  REPOSITORY_OWNER: kudrinyaroslav
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout template
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY_OWNER }}/${{ env.TEMPLATE_REPO_NAME }}
        ref: main
        token: ${{ secret.GITHUB_TOKEN }}
        fetch-depth: 0
        path: ./template
        
    - name: Checkout child
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY_OWNER }}/${{ env.CHILD_REPO_NAME }}
        fetch-depth: 0
        path: ./child
        
    - name: Check if branch exists
      run: |
        cd child
        if git branch -a | grep "origin/${{ env.TEMP_BRANCH_NAME }}"; then
         git push origin --delete ${{ env.TEMP_BRANCH_NAME }}
        fi

    - name: Copy files to child
      run: |
       cp -r ./template/* ./child/
       ls ./child
       cd child
       git branch
       
    - name: Commit changes
      run: |
          cd child
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ env.TEMP_BRANCH_NAME }}
          git add .
          git commit -m "Copy files from template to child"
          ls
          git push --set-upstream origin ${{ env.TEMP_BRANCH_NAME }}
    - name: Commit changes
      run: |
          curl -s -X POST -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ env.REPOSITORY_OWNER }}/${{ env.CHILD_REPO_NAME }}/pulls" -d '{"head":"${{ env.TEMP_BRANCH_NAME }}","base":"${{ env.CHILD_MAIN_BRANCH }}","title":"Update from template repository"}'
