name: sync wiht template
on:
  push:
#   schedule:
#   - cron: '*/10 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout template repository
      uses: actions/checkout@v2
      with:
        repository: kudrinyaroslav/child
        ref: main
        
    - name: Setup SSH agent
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_rsa
        
    - name: Push changes to child repository
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git push -f git@github.com:kudrinyaroslav/child.git HEAD:main
